/**
 * Signal Model
 * Represents a trading signal generated by the analysis
 */

const { DataTypes, Model } = require('sequelize');

class Signal extends Model {
  static init(sequelize) {
    super.init({
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      user_id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
          model: 'users',
          key: 'id'
        }
      },
      // Asset information
      asset_symbol: {
        type: DataTypes.STRING(20),
        allowNull: false,
        comment: 'Trading asset symbol (AAPL, EURUSD, BTCUSD)'
      },
      asset_name: {
        type: DataTypes.STRING(255),
        allowNull: false,
        comment: 'Full asset name'
      },
      asset_type: {
        type: DataTypes.ENUM('stock', 'forex', 'crypto', 'commodity', 'index'),
        allowNull: false,
        comment: 'Type of asset'
      },
      // Signal data
      signal_type: {
        type: DataTypes.ENUM('BUY', 'SELL', 'HOLD', 'WAIT'),
        allowNull: false,
        comment: 'Signal type (BUY=CALL, SELL=PUT)'
      },
      trade_type: {
        type: DataTypes.ENUM('CALL', 'PUT'),
        allowNull: true,
        comment: 'Trade direction for binary options'
      },
      confidence_score: {
        type: DataTypes.INTEGER,
        allowNull: false,
        validate: {
          min: 0,
          max: 100
        },
        comment: 'Confidence score (0-100%)'
      },
      strength: {
        type: DataTypes.ENUM('WEAK', 'MODERATE', 'STRONG', 'VERY_STRONG'),
        allowNull: false,
        comment: 'Signal strength based on indicator agreement'
      },
      // Price data
      current_price: {
        type: DataTypes.DECIMAL(15, 5),
        allowNull: false,
        comment: 'Current price when signal was generated'
      },
      target_price_up: {
        type: DataTypes.DECIMAL(15, 5),
        allowNull: true,
        comment: 'Target price for upward movement'
      },
      target_price_down: {
        type: DataTypes.DECIMAL(15, 5),
        allowNull: true,
        comment: 'Target price for downward movement'
      },
      stop_loss_price: {
        type: DataTypes.DECIMAL(15, 5),
        allowNull: true,
        comment: 'Suggested stop loss price'
      },
      // Technical indicators data (stored as JSON)
      indicators: {
        type: DataTypes.TEXT,
        allowNull: false,
        comment: 'JSON string of all indicator values',
        get() {
          const rawValue = this.getDataValue('indicators');
          return rawValue ? JSON.parse(rawValue) : {};
        },
        set(val) {
          this.setDataValue('indicators', JSON.stringify(val));
        }
      },
      // Indicator scores
      rsi_score: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment: 'RSI indicator score (-2 to +2)'
      },
      macd_score: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment: 'MACD indicator score (-2 to +2)'
      },
      bollinger_score: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment: 'Bollinger Bands indicator score (-1 to +1)'
      },
      ema_score: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment: 'EMA indicator score (-1 to +1)'
      },
      sma_score: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment: 'SMA indicator score (-1 to +1)'
      },
      stochastic_score: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment: 'Stochastic indicator score (-1 to +1)'
      },
      volume_score: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment: 'Volume indicator score (-1 to +1)'
      },
      // Market conditions
      market_trend: {
        type: DataTypes.ENUM('BULLISH', 'BEARISH', 'SIDEWAYS', 'VOLATILE'),
        allowNull: true,
        comment: 'Overall market trend'
      },
      volatility_level: {
        type: DataTypes.ENUM('LOW', 'MEDIUM', 'HIGH', 'EXTREME'),
        allowNull: true,
        comment: 'Market volatility level'
      },
      volume_trend: {
        type: DataTypes.ENUM('INCREASING', 'DECREASING', 'STABLE'),
        allowNull: true,
        comment: 'Volume trend'
      },
      // Trading recommendations
      recommended_amount: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: true,
        comment: 'Recommended trade amount'
      },
      recommended_duration: {
        type: DataTypes.INTEGER,
        allowNull: true,
        comment: 'Recommended trade duration in minutes'
      },
      risk_level: {
        type: DataTypes.ENUM('LOW', 'MEDIUM', 'HIGH'),
        allowNull: true,
        comment: 'Risk level assessment'
      },
      // Metadata
      source: {
        type: DataTypes.ENUM('technical_analysis', 'manual', 'api', 'alert'),
        defaultValue: 'technical_analysis',
        comment: 'How the signal was generated'
      },
      timeframe: {
        type: DataTypes.STRING(10),
        defaultValue: '1D',
        comment: 'Timeframe used for analysis'
      },
      strategy_used: {
        type: DataTypes.STRING(100),
        allowNull: true,
        comment: 'Trading strategy that generated this signal'
      },
      // Status and validity
      status: {
        type: DataTypes.ENUM('ACTIVE', 'EXPIRED', 'EXECUTED', 'REJECTED'),
        defaultValue: 'ACTIVE',
        comment: 'Signal status'
      },
      expires_at: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'When the signal expires'
      },
      executed_at: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'When the signal was executed'
      },
      // Performance tracking
      success_rate: {
        type: DataTypes.DECIMAL(5, 2),
        allowNull: true,
        comment: 'Historical success rate for similar signals'
      },
      backtest_result: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: 'Backtesting results for this signal type'
      },
      // Additional data
      notes: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: 'Additional notes about the signal'
      },
      tags: {
        type: DataTypes.STRING(500),
        allowNull: true,
        comment: 'Comma-separated tags'
      },
      // Timestamps
      created_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW
      }
    }, {
      sequelize,
      modelName: 'Signal',
      tableName: 'signals',
      indexes: [
        {
          fields: ['user_id']
        },
        {
          fields: ['asset_symbol']
        },
        {
          fields: ['signal_type']
        },
        {
          fields: ['confidence_score']
        },
        {
          fields: ['status']
        },
        {
          fields: ['created_at']
        },
        {
          fields: ['expires_at']
        }
      ]
    });

    return this;
  }

  /**
   * Calculate total score from all indicators
   */
  getTotalScore() {
    return this.rsi_score + this.macd_score + this.bollinger_score +
           this.ema_score + this.sma_score + this.stochastic_score + this.volume_score;
  }

  /**
   * Check if signal is still valid
   */
  isValid() {
    if (this.status !== 'ACTIVE') return false;
    if (this.expires_at && new Date() > this.expires_at) return false;
    return true;
  }

  /**
   * Check if signal meets confidence threshold
   */
  meetsConfidence(minConfidence = 75) {
    return this.confidence_score >= minConfidence;
  }

  /**
   * Get signal quality description
   */
  getQuality() {
    const score = this.confidence_score;
    if (score >= 90) return 'Excellent';
    if (score >= 80) return 'Very Good';
    if (score >= 70) return 'Good';
    if (score >= 60) return 'Fair';
    return 'Poor';
  }

  /**
   * Get recommended trade parameters
   */
  getTradeRecommendation() {
    return {
      direction: this.trade_type,
      amount: this.recommended_amount || 5,
      duration: this.recommended_duration || 5,
      confidence: this.confidence_score,
      risk_level: this.risk_level || 'MEDIUM'
    };
  }

  /**
   * Format signal for display
   */
  toDisplayFormat() {
    return {
      id: this.id,
      asset: `${this.asset_symbol} (${this.asset_name})`,
      signal: this.signal_type,
      type: this.trade_type,
      confidence: `${this.confidence_score}%`,
      strength: this.strength,
      quality: this.getQuality(),
      current_price: this.current_price,
      indicators: this.indicators,
      created_at: this.created_at.toLocaleString(),
      expires_at: this.expires_at ? this.expires_at.toLocaleString() : null
    };
  }

  /**
   * Mark signal as executed
   */
  markExecuted() {
    this.status = 'EXECUTED';
    this.executed_at = new Date();
    this.updated_at = new Date();
  }

  /**
   * Mark signal as expired
   */
  markExpired() {
    this.status = 'EXPIRED';
    this.updated_at = new Date();
  }

  /**
   * Get indicator summary
   */
  getIndicatorSummary() {
    const indicators = this.indicators;
    return {
      rsi: indicators.rsi || null,
      macd: indicators.macd || null,
      bollinger: indicators.bollinger || null,
      ema: indicators.ema || null,
      sma: indicators.sma || null,
      stochastic: indicators.stochastic || null,
      volume: indicators.volume || null
    };
  }
}

module.exports = Signal;